version: '3.7'

services:
  client:
    image: ${DOCKER_BASE}-client:latest
    ports:
      - ${CLIENT_PORT}:3000
    volumes:
      - ./client:/app
      - node_modules2:/app/node_modules
    command: ["dev"]
    environment:
      - PORT=3000
      - SERVER_URL
      - CLIENT_URL
    depends_on:
      - server
    networks:
      - nginx-proxy

  server:
    image: ${DOCKER_BASE}-server:latest
    ports:
      - ${PORT}:3000
    command: ["start:dev"]
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      - SECRET
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - BUCKET
    volumes:
      - ./server:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
    networks:
      - nginx-proxy
      - default

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./server/data/postgres:/var/lib/postgresql/data
      - ~/.pgpass:/root/.pgpass
    networks:
      - default

networks:
  default:
  nginx-proxy:
    external: true

volumes:
  node_modules:
  node_modules2:
